[build]
  command = "yarn run build"
  publish = "public/"

[dev]
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[functions]
  node_bundler = "esbuild"
